name: AndroidBuild  # 工作流名称

on:  # on:事件（工作流在什么情况下被触发）
  push:  # 推送
    branches: [ master ]  # branches:分支（主分支）
  pull_request:  # 拉取请求
    branches: [ master ]  # branches:分支（主分支）

jobs:  # 工作任务（一个或多个）
  build:  # 构建（为Android项目构建APK任务）（需要指定运行环境Ubuntu、MacOS或WindowsOS）
    runs-on: ubuntu-latest  # runs-on:运行环境（ubuntu-latest）
    steps:  # 编写步骤

      # 下载源码（检查主分支master，并从主分支master下载）
      - name: Checkout
        uses: actions/checkout@v6.1.0  # 导入开源（actions/checkout@v6.1.0）

      # 配置JDK环境
      - name: Setup Java JDK
        uses: actions/setup-java@v6.0.0  # 导入开源（actions/setup-java@v6.0.0）
        with:
          java-version: '17' # 版本号
          distribution: 'temurin' # 发行版

      # 修改权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      # 打包构建（构建Gradle）
      - name: Build with Gradle
        run: ./gradlew build  # 运行

      # 上传构建（Android项目生成APK）
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1  # 导入开源（actions/upload-artifact@v7.0.1）
        with:
          name: AGAPKCICD.apk # APK名称（项目名称.apk）
          path: app/build/outputs/apk/debug/app-debug.apk # APK路径（与Android Studio构建APK路径一样）

      # 部署到应用市场-需要Actions secrets创建的变量（应用市场：‌华为应用市场、应用宝等）
      # 这里就不介绍，以后再部署